name: verifi
description: The future of global WiFi access
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  appspector: ^0.9.0
  auto_connect:
    git:
      url: https://github.com/VeriFi-World/Auto-Connect.git
      ref: main
  auto_size_text: ^3.0.0
  badges: ^2.0.3
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.0
  connectivity_plus: ^3.0.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_analytics: ^10.0.8
  firebase_app_check: ^0.1.1+7
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.8
  flutter_launcher_icons: ^0.11.0
  flutter_map: ^3.1.0
  flutter_map_supercluster: ^2.2.0
  flutter_radar: ^3.1.3
  flutter_riverpod: ^2.1.3
  flutter_svg: ^1.1.6
  flutter_typeahead: ^4.1.0
  font_awesome_flutter: ^10.3.0
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  go_router: ^6.0.0
  http: ^0.13.5
  latlong2: ^0.8.1
  network_info_plus: ^3.0.0
  phone_form_field: ^7.0.5
  pinput: ^2.2.20
  random_avatar: ^0.0.7
  riverpod_annotation: ^1.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  url_launcher: ^6.1.7

dependency_overrides:
  font_awesome_flutter:
    path: assets/font_awesome_flutter/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  coverage: ^1.6.1
  dependency_validator: ^3.2.2
  firebase_auth_mocks: ^0.9.2
  flutter_lints: ^2.0.1
  golden_toolkit: ^0.14.0
  json_serializable: ^6.5.4
  meta: ^1.8.0
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  riverpod_generator: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/google_fonts/
    - assets/launcher_icon/
    - assets/social_media_icons/
    - assets/wallet_logos/
    - assets/wifi_markers/
