name: verifi
description: Bridging the universe with the metaverse

version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.0
  async: ^2.8.0
  auto_size_text: ^3.0.0
  bloc: ^8.0.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.0
  equatable: ^2.0.0
  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.0
  firebase_crashlytics: ^2.5.0
  fluster: ^1.2.0
  flutter_bloc: ^8.0.0
  flutter_cache_manager: ^3.3.0
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: ^9.4.0
  flutter_picker: ^2.0.0
  formz: ^0.4.1
  geoflutterfire: ^3.0.3
  geolocator: ^8.2.0
  google_fonts: ^3.0.0
  google_maps_flutter: ^2.1.0
  google_place: ^0.4.7
  http: ^0.13.0
  hydrated_bloc: ^8.1.0
  json_theme: ^4.0.0
  page_transition: ^2.0.0
  palette_generator: ^0.3.0
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  pinput: ^2.2.0
  phone_form_field: ^5.0.0
  sembast: ^3.1.0
  scroll_snap_list: ^0.9.0
  shared_preferences: ^2.0.0
  spider: ^4.0.0
  stream_transform: ^2.0.0
  url_launcher: ^6.1.0
  uuid: ^3.0.0
  walletconnect_dart: ^0.0.1
  firebase_app_check: ^0.0.6+18

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^3.0.0
  flutter_lints: ^1.0.0
  test: ^1.21.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/launcher_icon/
    - assets/profile_avatars/
    - assets/social_media_icons/
    - assets/wallet_logos/

flutter_icons:
  android: true
  ios: true
  image_path_android: 'assets/launcher_icon/vf_android.png'
  image_path_ios: 'assets/launcher_icon/vf_ios.png'
  adaptive_icon_foreground: 'assets/launcher_icon/vf_android.png'
  adaptive_icon_background: '#000000'
