name: verifi
description: The future of global WiFi access
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # appspector: ^0.9.0
  # auto_connect:
  #   git:
  #     url: https://github.com/VeriFi-World/Auto-Connect.git
  #     ref: main
  auto_size_text: ^3.0.0
  badges: ^3.1.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^4.5.0
  cloud_functions: ^4.1.0
  connectivity_plus: ^3.0.0
  easy_debounce: ^2.0.0
  enum_to_string: ^2.0.0
  equatable: ^2.0.0
  flutter_animate: ^4.1.0
  firebase_app_check: ^0.1.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_crashlytics: ^3.1.0
  firebase_messaging: ^14.4.0
  flutter_gif: ^0.0.4
  flutter_local_notifications: ^13.0.0
  flutter_map: ^3.1.0
  flutter_map_supercluster: ^2.2.0
  flutter_radar: ^3.1.0
  flutter_riverpod: ^2.1.0
  flutter_svg: ^2.0.0
  flutter_typeahead: ^4.1.0
  font_awesome_flutter: ^10.3.0
  geolocator: ^9.0.0
  google_fonts: ^4.0.0
  go_router: ^6.0.0
  http: ^0.13.0
  latlong2: ^0.8.0
  lottie: ^2.3.0
  network_info_plus: ^3.0.0
  permission_handler: ^10.2.0
  phone_form_field: ^7.1.0
  pin_code_fields: ^7.4.0
  random_avatar: ^0.0.8
  riverpod_annotation: ^2.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.0
  shimmer: ^2.0.0
  stack_trace: ^1.11.0
  tuple: ^2.0.0
  url_launcher: ^6.1.0

dependency_overrides:
  font_awesome_flutter:
    path: assets/font_awesome_flutter/

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.3.0
  coverage: ^1.6.0
  dependency_validator: ^3.2.0
  fake_cloud_firestore: ^2.3.0
  firebase_auth_mocks:
    path: ../../forks/firebase_auth_mocks
  flutter_lints: ^2.0.0
  freezed: ^2.3.0
  golden_toolkit: ^0.15.0
  json_serializable: ^6.5.0
  mocktail: ^0.3.0
  riverpod_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/google_fonts/
    - assets/launcher_icon/
    - assets/lottie_animations/
    - assets/social_media_icons/
    - assets/wallet_logos/
    - assets/wifi_markers/
  fonts:
    - family: FixedFontAwesomeIcons
      fonts:
        - asset: assets/fonts/FixedFontAwesomeIcons.ttf
