name: verifi
description: Connect Without Limits
version: 0.0.1+12
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  badges: ^2.0.3
  cached_network_image: ^3.2.0
  cloud_firestore: ^4.0.0
  equatable: ^2.0.0
  firebase_analytics: ^10.0.0
  firebase_app_check: ^0.1.0
  firebase_auth: ^4.0.0
  firebase_core: ^2.1.0
  firebase_crashlytics: ^3.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_map: ^3.0.0
  flutter_map_supercluster: ^2.1.1
  flutter_riverpod: ^2.1.0
  flutter_svg: ^1.1.0
  geolocator: ^9.0.0
  google_fonts: ^3.0.0
  go_router: ^5.2.0
  http: ^0.13.0
  latlong2: ^0.8.0
  phone_form_field: ^7.0.0
  pinput: ^2.2.0
  random_avatar: ^0.0.7
  riverpod_annotation: ^1.0.0
  shared_preferences: ^2.0.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  dependency_validator: ^3.0.0
  firebase_auth_mocks: ^0.9.0
  flutter_lints: ^1.0.0
  json_serializable: ^6.5.0
  riverpod_generator: ^1.0.0
  test: ^1.21.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/google_fonts/
    - assets/launcher_icon/
    - assets/social_media_icons/
    - assets/wallet_logos/
    - assets/wifi_markers/
