import 'package:fluster/fluster.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:google_place/google_place.dart';
import 'package:verifi/blocs/blocs.dart';
import 'package:verifi/models/wifi_details.dart';

/// A single WiFi access point or a cluster of WiFi access points.
/// [id] is either the unique ID auto-generated by Firestore, or a
class AccessPoint extends Clusterable {
  final String id;
  final DetailsResult? placeDetails;
  final WifiDetails? wifiDetails;
  final LatLng? clusterLocation;
  BitmapDescriptor? icon;
  List<AccessPoint>? points;

  AccessPoint({
    required this.id,
    this.placeDetails,
    this.wifiDetails,
    this.clusterLocation,
    this.icon,
    this.points,
    bool isCluster = false,
    int? clusterId,
    int? pointsSize,
    String? childMarkerId,
  }) : super(
          markerId: id,
          latitude: (wifiDetails != null)
              ? wifiDetails.location.latitude
              : clusterLocation?.latitude,
          longitude: (wifiDetails != null)
              ? wifiDetails.location.longitude
              : clusterLocation?.longitude,
          isCluster: isCluster,
          clusterId: clusterId,
          pointsSize: pointsSize,
          childMarkerId: childMarkerId,
        );

  factory AccessPoint.fromJson(Map<String, dynamic> json) {
    return AccessPoint(
      id: json['id'],
      placeDetails: DetailsResult.fromJson(json['placeDetails']),
      wifiDetails: WifiDetails.fromJson(json['wifiDetails']),
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'placeDetails': _placeDetailsToJson(),
        'wifiDetails': wifiDetails?.toJson(),
      };

  @override
  String toString() => "AccessPoint: { id: $id, icon: $icon }";

  Marker toMarker(BuildContext context) {
    final marker = Marker(
      markerId: MarkerId((wifiDetails != null) ? wifiDetails?.id ?? id : id),
      position: (wifiDetails != null)
          ? LatLng(
              wifiDetails?.location.latitude ?? -1.0,
              wifiDetails?.location.longitude ?? -1.0,
            )
          : LatLng(clusterLocation?.latitude ?? -1.0,
              clusterLocation?.longitude ?? -1.0),
      icon: icon ?? BitmapDescriptor.defaultMarker,
      onTap: () {
        MapUtils.showMarkerInfoSheet(context, this);
        if (isCluster == false) {
          context
              .read<MapCubit>()
              .mapController
              ?.animateCamera(CameraUpdate.newLatLngZoom(
                LatLng(
                  wifiDetails?.location.latitude ?? -1.0,
                  wifiDetails?.location.longitude ?? -1.0,
                ),
                19,
              ));
        }
      },
    );
    return marker;
  }

  Map<String, dynamic> _placeDetailsToJson() {
    return {
      'icon': placeDetails?.icon,
      'geometry': {
        'location': {
          'lat': placeDetails?.geometry?.location?.lat,
          'lng': placeDetails?.geometry?.location?.lng,
        },
      },
      'name': placeDetails?.name,
      'photos': (placeDetails?.photos != null)
          ? placeDetails?.photos
              ?.map((photo) => {
                    'photo_reference': photo.photoReference,
                    'height': photo.height,
                    'width': photo.width,
                    'html_attributions': photo.htmlAttributions,
                  })
              .toList()
          : null,
      'place_id': placeDetails?.placeId,
      'formatted_address': placeDetails?.formattedAddress,
    };
  }
}
