// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjC3_3a_u-nEUD11nSPJzwhm0KZ0fKQz8',
    appId: '1:120678530892:android:21194af32fd5ef804499e9',
    messagingSenderId: '120678530892',
    projectId: 'verifi-5db5b',
    storageBucket: 'verifi-5db5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_cJqUivOjF23bjjjldVhpsFSEmGW9fuU',
    appId: '1:120678530892:ios:c4cba8aa6d9c1bc44499e9',
    messagingSenderId: '120678530892',
    projectId: 'verifi-5db5b',
    storageBucket: 'verifi-5db5b.appspot.com',
    androidClientId: '120678530892-9db7a4q9ail5n9i3qnji466rsqcs9871.apps.googleusercontent.com',
    iosClientId: '120678530892-6r5tcaocaodrbmfhjjc782rvghjpo7g7.apps.googleusercontent.com',
    iosBundleId: 'world.verifi.app',
  );
}
