name: verifi

on:
  pull_request:
    paths:
      - ".github/workflows/verifi.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/verifi.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'

      - name: Clean
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze lib test

      - name: Run Tests
        run: |
          flutter test